# Generated by Django 5.0.1 on 2024-02-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='workout_type',
        ),
        migrations.AddField(
            model_name='workout',
            name='workouts',
            field=models.JSONField(default=dict),
        ),
    ]
