# Generated by Django 5.0.1 on 2024-02-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_workout_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workouts',
            field=models.JSONField(default=list),
        ),
    ]
